def find_group(n):
    global count
    a = []
    for i in range(n):
        count = 0
        while i > 0:
            k = i % 10
            count += k
            i = i // 10
        a.append(count)
    for j in range(0, count + 1):
        x = a.count(j)
        print("В группе", j + 1, "количество покупателей =", x)


n_customers = int(input())
find_group(n_customers)
